apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: jatra
type: Opaque
stringData:
  access-secret: "your-jwt-access-secret-min-32-chars-change-in-production-now"
  refresh-secret: "your-jwt-refresh-secret-min-32-chars-change-in-production-now"
